"""migrate

Revision ID: 9cc7f5833319
Revises: 70858f3f710a
Create Date: 2020-01-27 23:20:28.438844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc7f5833319'
down_revision = '70858f3f710a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
